### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Daggerbot** [Daggerbot/mm#1]
General
- [ ] Find someone to help with a Cocoa port. Possibly Android and iOS in the future.
- [ ] After Rust 1.0.0 is released, if `std::num::NumCast` is stable, remove dependence on `num` crate.

Windows
- [ ] Handle `attr.screen` in `Window::new`.

Windows events
- [x] `ButtonEvent`
- [x] `FocusEvent`
- [ ] `KeyEvent`
- [x] `MotionEvent`
- [x] `UserEvent`
- [x] `VisibilityEvent`
- [x] `WheelEvent`

X11 events
- [ ] `ButtonEvent`
- [ ] `FocusEvent`
- [ ] `KeyEvent`
- [ ] `MotionEvent`
- [ ] `UserEvent`
- [ ] `VisibilityEvent`
- [ ] `WheelEvent`
